/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'addDepartment' : ActorMethod<
    [string, Array<string>, Array<string>],
    undefined
  >,
  'addEmployee' : ActorMethod<[string, string], undefined>,
  'addQueue' : ActorMethod<[string, string], undefined>,
  'checkInVisitor' : ActorMethod<
    [string, bigint, string, [] | [string]],
    undefined
  >,
  'createAdminLogs' : ActorMethod<[string, string], undefined>,
  'createNewId' : ActorMethod<[bigint], bigint>,
  'getAdminLogs' : ActorMethod<[], Array<[string, string]>>,
  'getDepartments' : ActorMethod<[], Array<[string, Array<string>]>>,
  'getEmployees' : ActorMethod<[], Array<[string, string]>>,
  'getQueues' : ActorMethod<[], Array<[string, Array<string>]>>,
  'getVisitorCheckinRecords' : ActorMethod<[], Array<[bigint, string]>>,
  'updateQueueMode' : ActorMethod<[string], undefined>,
  'viewQueueStatus' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];