/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addDepartment' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addQueue' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkInVisitor' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'createAdminLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createNewId' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAdminLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getDepartments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getEmployees' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getQueues' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getVisitorCheckinRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'updateQueueMode' : IDL.Func([IDL.Text], [], []),
  'viewQueueStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addDepartment' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addQueue' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkInVisitor' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'createAdminLogs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createNewId' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAdminLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getDepartments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getEmployees' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getQueues' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getVisitorCheckinRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'updateQueueMode' : IDL.Func([IDL.Text], [], []),
    'viewQueueStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };